// SPDX-FileCopyrightText: no
// SPDX-License-Identifier: CC0-1.0
#ifndef CALAMARES_VERSION_H
#define CALAMARES_VERSION_H

/* #undef CALAMARES_ORGANIZATION_NAME */
/* #undef CALAMARES_ORGANIZATION_DOMAIN */
/* #undef CALAMARES_APPLICATION_NAME */
/* #undef CALAMARES_VERSION */
/* #undef CALAMARES_VERSION_SHORT */

/* #undef CALAMARES_VERSION_MAJOR */
/* #undef CALAMARES_VERSION_MINOR */
/* #undef CALAMARES_VERSION_PATCH */
/* #undef CALAMARES_VERSION_RC */

#endif  // CALAMARES_VERSION_H
